/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 brain.glb 
Author: maheshshinde777 (https://sketchfab.com/maheshshinde777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-735ca31a3b22433281e6fa9606792faa
Title: Brain
*/

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'

export function Brain(props) {
  const { nodes, materials } = useGLTF('/models/brain.glb')
  return (
    <>
    <OrbitControls />
    <hemisphereLight intensity={1} />
    <group {...props} dispose={null} position={[0,0.5,0]}>
      <mesh geometry={nodes.Icosphere__0.geometry} material={materials['Scene_-_Root']} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.25} />
    </group>
    </>
  )
}

useGLTF.preload('/models/brain.glb')
