/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 intestines.glb 
Author: antonia.sundberg (https://sketchfab.com/antonia.sundberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-and-large-intestine-8a1ca8e3ca224cdeb9264674416bde38
Title: Small and large intestine
*/

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'

export function Intestines(props) {
  const { nodes, materials } = useGLTF('/models/intestines.glb')
  return (
    <>
    <OrbitControls />
    <hemisphereLight intensity={0.75} />
    <pointLight intensity={1} position={[2, -2, 1]} />
    <group {...props} dispose={null} scale={3} position={[-2,-0.5,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.037}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[15.286, 3.827, -1.997]} scale={0.1}>
            <mesh geometry={nodes.Tjocktarm_Default_Material_0.geometry} material={materials.Default_Material} />
            <mesh geometry={nodes.Tjocktarm_Default_Material_0_1.geometry} material={materials.Default_Material} />
          </group>
          <mesh geometry={nodes.Tunntarm_Default_Material_0.geometry} material={materials.Default_Material_0} position={[14.166, 10.696, 1.169]} scale={0.1} />
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/models/intestines.glb')
