/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 lungs.glb 
Author: neshallads (https://sketchfab.com/neshallads)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-human-lungs-ce09f4099a68467880f46e61eb9a3531
Title: Realistic Human Lungs
*/

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'

export function Lungs(props) {
  const { nodes, materials } = useGLTF('/models/lungs.glb')
  return (
    <>
    <OrbitControls/>
    <hemisphereLight intensity={1} />
    <group {...props} dispose={null} scale={0.16} position={[0,-1.5,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.85}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <mesh geometry={nodes.thairoid01low_part01_Group6344Group18522_thairoid01lungh_part01_0.geometry} material={materials.thairoid01lungh_part01} scale={17.228} />
          <mesh geometry={nodes.thairoid01low_part02_Group6344Group24638_thairoid01lungh_part02_0.geometry} material={materials.thairoid01lungh_part02} scale={17.228} />
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/models/lungs.glb')
