/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 stomach.glb 
Author: Vikrama Raghuraman (https://sketchfab.com/vikrama1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stomach-f4ccc8dd0f124d2d9f1d8d4db676e217
Title: Stomach
*/

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'

export function Stomach(props) {
  const { nodes, materials } = useGLTF('/models/stomach.glb')
  return (
    <>
    <OrbitControls />
    <hemisphereLight intensity={1} />
    <group {...props} dispose={null} scale={0.45} position={[0,1,0]}>
      <group position={[-0.046, 3.375, 0]} scale={[0.4, 1, 0.405]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/models/stomach.glb')
